### ISSUE TITLE
Västtrafik API changes possibly affects us

### ISSUE THREAD

**Issue by kchr** [ltworf/pysttrafik#6]
Hi,

I just received an API change announcement from Västtrafik Labs (their API developers).

**TL;DR** Basically, this boils down to these changes:

1. All requests need to be GET - historically POST requests have been accepted
2. Specific API version number needs to be correct - non-existant versions will throw error

We will not be affected by the first one (only GET is used). I don't think we're using specific API version calls either, but let's audit the code to be sure. :-)

Rollout timeframe is about a week away (between 22-26th of June).

Original announcement (sorry, Swedish only):

> Hej,
> 
> Enligt våra uppgifter har du visat intresse för Västtrafiks API för
> Reseplanering genom att registrera dig på labs.vasttrafik.se. Av denna
> anledning vill vi på nytt informera om att Västtrafik nu genomför en satsning
> inom området API Management. Vad denna satsning omfattar och vad den innebär
> för dig tänkte vi kortfattat beskriva i detta mail.
> 
> API Gateway
> 
> Det första som kommer att hända, och som kan påverka dig, är att vi under vecka
> 26 (22-26 Juni) kommer att dirigera om all API-trafik till att gå via en s.k.
> API Gateway. Denna förändring kommer inte att påverka adressen till vårt
> Reseplanerar-API. Däremot är det så att anrop som idag fungerar, men som är
> direkt felaktiga, inte längre kommer att släppas fram till vårt API. Några
> exempel på felaktiga anrop som vi har hittat i våra logfiler är:
> 
> 1. Användning av POST istället för GET. Alla anrop till vårt Reseplanerar-API är GET, så om du idag använder POST behöver du snarast byta till GET.
> 
> 2. Resurser som inte finns
>  * Fel: /bin/rest.exe/v1departureBoard (saknas ett / efter v1)
>  * Fel: /bin/rest.exe//v1.07//departureBoard (felaktig användning av // samt version som inte finns)

Regards,
kchr

**Comment by ltworf** [comment]
Thanks for your report!

It should be Ok I suppose, all the HTTP requests are performed by a single function that uses GET.
